### ISSUE TITLE
example9/kvsput-usrdata.py: KeyError with FLUX_JOB_KVSPATH environment variable

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-workflow-examples#28]
Submitting `kvsput-usrdata.py` with the new execution system results in the following KeyError:

```
bash-4.2$ flux mini submit -N 1 -n 1 ./kvsput-usrdata.py 
304674242560
bash-4.2$ flux job attach 304674242560
flux-job: task(s) exited with exit code 1
Traceback (most recent call last):
  File "./kvsput-usrdata.py", line 9, in <module>
    job_path = os.environ['FLUX_JOB_KVSPATH']
  File "/usr/tce/packages/python/python-2.7.16/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'FLUX_JOB_KVSPATH'
```

It looks like `FLUX_JOB_KVSPATH` was set with `wreck` (in **src/modules/wreck/wrexecd.c** I believe), which is no longer used.

**Comment by cmoussa1** [comment]
This issue was resolved with PR #42.
