### ISSUE TITLE
example7: job_state_cb not watching state transitions

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-workflow-examples#60]
When running **bookkeeper.py** in example7 against the latest version of Flux, it looks like the the job-state transitions are not being kept track of after the jobs are submitted:

```
[moussa1@opal161:example7]$ ./bookkeeper.py 3
5062608814080
5062944358400
5063363788800
5063783219200
5064236204032
5064672411648
bookkeeper: all jobs submitted
bookkeeper: waiting until all jobs complete
bookkeeper: all jobs completed
[moussa1@opal161:example7]$ flux jobs
             JOBID USER     NAME       STATE    NTASKS TIME
     5064672411648 moussa1  io-forward RUN           3 2.2s
     5064236204032 moussa1  compute.py RUN           6 2.2s
     5063783219200 moussa1  io-forward RUN           3 2.3s
     5063363788800 moussa1  compute.py RUN           6 2.3s
     5062944358400 moussa1  io-forward RUN           3 2.3s
     5062608814080 moussa1  compute.py RUN           6 2.4s
```

I tried running a similar script in [flux-core](https://github.com/flux-framework/flux-core/blob/29084e328b15b895f1c2040e11b0a6d3229c1647/t/job-manager/bulk-state.py): `src/t/job-manager/bulk-state.py`, and I get this error:

```
[moussa1@opal161:example7]$ flux python bulk-state.py 3
Exception ignored in: <bound method Wrapper.__del__ of <flux.core.handle.Flux object at 0x2aaaac140b70>>
Traceback (most recent call last):
  File "/usr/lib64/flux/python3.6/flux/wrapper.py", line 363, in __del__
  File "/usr/lib64/flux/python3.6/flux/wrapper.py", line 339, in _clear
  File "/usr/lib64/flux/python3.6/flux/wrapper.py", line 166, in __call__
ReferenceError: weakly-referenced object no longer exists
```

Although there is already an issue being tracked there @ [#2671](https://github.com/flux-framework/flux-core/issues/2671).

**Comment by grondo** [comment]
The exception from `bulk-state.py` can be ignored. I think they happen after the script successfully exits. I added some print debug to the script and see:

```console
$ flux python ./job-manager/bulk-state.py 3
Submitted 3 jobs
job 8524201459712 moved to state DEPEND
job 8524201459712 moved to state SCHED
job 8524201459712 moved to state RUN
job 8524453117952 moved to state DEPEND
job 8524453117952 moved to state SCHED
job 8524453117952 moved to state RUN
job 8525191315456 moved to state DEPEND
job 8525191315456 moved to state SCHED
job 8525191315456 moved to state RUN
job 8524201459712 moved to state CLEANUP
job 8524201459712 moved to state INACTIVE
job 8525191315456 moved to state CLEANUP
job 8524453117952 moved to state CLEANUP
job 8525191315456 moved to state INACTIVE
job 8524453117952 moved to state INACTIVE
Success.
Exception ignored in: <bound method Wrapper.__del__ of <flux.core.handle.Flux object at 0x2aaab26a78d0>>
Traceback (most recent call last):
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/wrapper.py", line 363, in __del__
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/wrapper.py", line 339, in _clear
  File "/g/g0/grondo/git/flux-core.git/src/bindings/python/flux/wrapper.py", line 166, in __call__
ReferenceError: weakly-referenced object no longer exists
``` 

```diff
diff --git a/t/job-manager/bulk-state.py b/t/job-manager/bulk-state.py
index b860e00..2a6ed5b 100755
--- a/t/job-manager/bulk-state.py
+++ b/t/job-manager/bulk-state.py
@@ -39,6 +39,7 @@ def parse_notification(jobs, msg):
         jobid = entry[0]
         state = entry[1]
         if jobid in jobs:
+            print("job {} moved to state {}".format(jobid, state))
             jobs[jobid].append(state)
 
 
@@ -65,6 +66,8 @@ for i in range(njobs):
     jobid = job.submit(h, jobspec)
     jobs[jobid] = ["NEW"]
 
+print("Submitted {} jobs".format(len(jobs)))
+
 # Process events until all jobs have reached INACTIVE state.
 while not all_inactive(jobs):
     event = h.event_recv()
@@ -76,6 +79,8 @@ for jobid in jobs:
         print("{}: {}: {}".format("bad state list", jobid, jobs[jobid]))
         sys.exit(1)
 
+print("Success.")
+
 # Unsubscribe to state notifications and close connection to broker.
 h.event_unsubscribe("job-state")
 

```

**Comment by grondo** [comment]
Can you paste the reproducer `bookkeeper.py` here for reference?

**Comment by cmoussa1** [comment]
Sure thing! 

```
#!/usr/bin/env python3

import json
import os
import argparse

import flux
from flux.job import JobspecV1

compute_jobreq = JobspecV1.from_command(
    command=["./compute.py", "10"], num_tasks=6, num_nodes=3, cores_per_task=2
)
compute_jobreq.cwd = os.getcwd()
compute_jobreq.environment = dict(os.environ)

io_jobreq = JobspecV1.from_command(
    command=["./io-forwarding.py", "10"], num_tasks=3, num_nodes=3, cores_per_task=1
)
io_jobreq.cwd = os.getcwd()
io_jobreq.environment = dict(os.environ)

njobs = 0


def job_state_cb(f, typemask, message, arg):
    global njobs
    N = args.integer
    for jobid, state, time in message.payload["transitions"]:
        print("job " + str(jobid) + " changed its state to " + str(state))
        if state == "INACTIVE":
            njobs += 1
        if njobs == N * 2:
            f.reactor_stop(f.get_reactor())


# submit bundles of jobs using flux.job.submit ()
def submit_bundles(f, N):
    f = flux.Flux()
    for i in range(0, N):
        print(flux.job.submit(f, compute_jobreq))
        print(flux.job.submit(f, io_jobreq))

    print("bookkeeper: all jobs submitted")


# main
def main():
    parser = argparse.ArgumentParser(
        description="submit and wait for the completion of "
        "N bundles, each consisting of compute "
        "and io-forwarding jobs"
    )
    parser.add_argument(
        "integer",
        metavar="N",
        type=int,
        help="the number of bundles to submit and wait",
    )
    global args
    args = parser.parse_args()

    f = flux.Flux()
    f.event_subscribe("job-state")
    f.msg_watcher_create(job_state_cb, 0, "job-state").start()
    submit_bundles(f, args.integer)
    print("bookkeeper: waiting until all jobs complete")
    f.reactor_run(f.get_reactor(), 0)
    print("bookkeeper: all jobs completed")


main()

# vi: ts=4 sw=4 expandtab
```

**Comment by grondo** [comment]
Hm, @cmoussa1 -- I ran this on the current master of flux-core (though I changed the commands for both jobs to `sleep 10`) and it seemed to work for me:

```console
$ flux python bookkeeper.py  1
17341081452544
17341383442432
bookkeeper: all jobs submitted
bookkeeper: waiting until all jobs complete
job 17341081452544 changed its state to DEPEND
job 17341081452544 changed its state to SCHED
job 17341081452544 changed its state to RUN
job 17341383442432 changed its state to DEPEND
job 17341383442432 changed its state to SCHED
job 17341081452544 changed its state to CLEANUP
job 17341081452544 changed its state to INACTIVE
job 17341383442432 changed its state to RUN
job 17341383442432 changed its state to CLEANUP
job 17341383442432 changed its state to INACTIVE
bookkeeper: all jobs completed
```

**Comment by grondo** [comment]
One note, there appears to be an extra `flux.Flux()` in `bookkeeper.py` -- though I doubt it has anything to do with the issue described here:
```diff
--- bookkeeper.py.orig	2020-02-03 13:52:33.487174000 -0800
+++ bookkeeper.py	2020-02-03 13:50:48.705106000 -0800
@@ -35,7 +35,6 @@
 
 # submit bundles of jobs using flux.job.submit ()
 def submit_bundles(f, N):
-    f = flux.Flux()
     for i in range(0, N):
         print(flux.job.submit(f, compute_jobreq))
         print(flux.job.submit(f, io_jobreq))
```

**Comment by cmoussa1** [comment]
It must be a problem on my end. I've been running the bookkeeper script against the latest system installed version of Flux:

```
[moussa1@opal154:example7]$ flux --version
commands:    		0.14.0
libflux-core:		0.14.0
broker:  		0.14.0
FLUX_URI:		local:///var/tmp/moussa1/flux-RXpqRR/0/local
build-options:
```

**Comment by grondo** [comment]
Can you try against the current master?

**Comment by cmoussa1** [comment]
Restarted and ran against the current master and it seemed to fix that issue I was running into! Not sure as to why I wasn't getting any state transition messages. 🤷‍♂️ I'll go ahead and close this issue.
